### ISSUE TITLE
自建git通过代理无法访问

### ISSUE THREAD

**Issue by chyroc** [zjx20/socks-cli#3]
公司的git需要使用vpn连接内网才可以访问。

下面的说明都是在vpn已经连接的情况下。

如题，在没有启动本应用的情况下，使用`https`或者`git@`均可以clone下来。

启动之后 :

```
socket-cli ➜  cti git:(master) ✗ git clone git@git.myself.com:who/repo.git
Cloning into 'repo'...
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by chyroc** [comment]
所以怎么可以指定哪些 域名/ip 不通过代理访问

**Comment by zjx20** [comment]
试试这个答案吧 https://stackoverflow.com/a/19524910

如果`no_proxy`环境变量可以解决你的问题，你可以将它放到`socksproxyenv`里面：
```bash
EXPORT_ENV no_proxy ".yourcompany"
```

**Comment by chyroc** [comment]
下面的讨论均在设置`no_proxy`之后。

supports/git里面：
```
#!/bin/bash
# The shebang is just a hint for editors.

# For git to support "git://" protocol
EXPORT_ENV GIT_PROXY_COMMAND "${SOCKS_CLI_DIR}/sh/socksified-connect.sh"

# For git to support "ssh://" protocol
EXPORT_ENV GIT_SSH "${SOCKS_CLI_DIR}/sh/socksified-ssh.sh"

# For git to support "http(s)://" protocol
EXPORT_ENV ALL_PROXY "socks5h://${SOCKS_PROXY}"
```

使用`https`没有问题。

使用`git@`就有问题：
```
socket-cli ➜  vvvvv gcl git@git. yourcompany.com:who/repo.git
Cloning into 'repo'...
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by zjx20** [comment]
是的，`no_proxy`是针对curl的设置，所以只对`https`协议有效。控制ssh协议的另一个地方是 `~/.ssh/config`，这个在上面stackoverflow的另一个答案中有所提及。这可能意味着，你不能通过socks-cli来自动管理ssh和git协议的代理。你需要手工配置`~/.ssh/config`实现某些host走代理而某些不走代理，然后在`socksproxyenv`添加`unset GIT_PROXY_COMMAND` 和 `unset GIT_SSH` ，以防止socks-cli影响手工配置。

**Comment by zjx20** [comment]
建议只使用 `https` 协议，可以使问题简单化。

当然，我提出解决方案只针对git命令。如果想要所有命令都支持这个路由特性，就得本地搭建一个支持路由选择的socks5服务器，然后将该服务器的地址设置给`socks-cli`。这不是`socks-cli`可以解决的问题，也不应该由它来解决。
